const { hairlineWidth } = require("nativewind/theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/features/**/*.{js,jsx,ts,tsx}",
    "./src/lib/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      screens: {
        xs: "400px",
      },
      fontFamily: {
        puffberry: ["Puffberry"],
        bitcount: ["BitcountPropSingle-400"],
        "bitcount-100": ["BitcountPropSingle-100"],
        "bitcount-200": ["BitcountPropSingle-200"],
        "bitcount-300": ["BitcountPropSingle-300"],
        "bitcount-400": ["BitcountPropSingle-400"],
        "bitcount-500": ["BitcountPropSingle-500"],
        "bitcount-600": ["BitcountPropSingle-600"],
        "bitcount-700": ["BitcountPropSingle-700"],
        "bitcount-800": ["BitcountPropSingle-800"],
        "bitcount-900": ["BitcountPropSingle-900"],
        lobster: ["LobsterTwo-Regular"],
        "lobster-400": ["LobsterTwo-Regular"],
        "lobster-400-italic": ["LobsterTwo-Italic"],
        "lobster-700": ["LobsterTwo-Bold"],
        "lobster-700-italic": ["LobsterTwo-BoldItalic"],
        "playpen-100": ["PlaypenSans-Thin"],
        "playpen-200": ["PlaypenSans-ExtraLight"],
        "playpen-300": ["PlaypenSans-Light"],
        "playpen-400": ["PlaypenSans-Regular"],
        "playpen-500": ["PlaypenSans-Medium"],
        "playpen-600": ["PlaypenSans-SemiBold"],
        "playpen-700": ["PlaypenSans-Bold"],
        "playpen-800": ["PlaypenSans-ExtraBold"],
        "tgl-0": ["tgl-0"],
        "tgl-0-italic": ["tgl-0-italic"],
        "tgl-31034": ["tgl-31034"],
        "tgl-31034-italic": ["tgl-31034-italic"],
        "digital-7": ["Digital-7"],
        "digital-7-italic": ["Digital-7-Italic"],
        "digital-7-mono": ["Digital-7-Mono"],
        "digital-7-mono-italic": ["Digital-7-Mono-Italic"],
        "victor-mono": ["VictorMono_400Regular"],
        "victor-mono-100": ["VictorMono_100Thin"],
        "victor-mono-200": ["VictorMono_200ExtraLight"],
        "victor-mono-300": ["VictorMono_300Light"],
        "victor-mono-400": ["VictorMono_400Regular"],
        "victor-mono-500": ["VictorMono_500Medium"],
        "victor-mono-600": ["VictorMono_600SemiBold"],
        "victor-mono-700": ["VictorMono_700Bold"],
        "victor-mono-100-italic": ["VictorMono_100Thin_Italic"],
        "victor-mono-200-italic": ["VictorMono_200ExtraLight_Italic"],
        "victor-mono-300-italic": ["VictorMono_300Light_Italic"],
        "victor-mono-italic": ["VictorMono_400Regular_Italic"],
        "victor-mono-500-italic": ["VictorMono_500Medium_Italic"],
        "victor-mono-600-italic": ["VictorMono_600SemiBold_Italic"],
        "victor-mono-700-italic": ["VictorMono_700Bold_Italic"],
      },
      boxShadow: {
        glass: "2px 2px 5px rgba(0, 0, 0, 0.05)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        fuscia: {
          50: "#fff3fe",
          100: "#ffe6fe",
          200: "#ffccfb",
          300: "#ffa3f6",
          400: "#ff6def",
          500: "#ff22ee",
          600: "#e316cf",
          700: "#bd0ea9",
          800: "#9a0e88",
          900: "#7e116d",
          950: "#550048",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [require("tailwindcss-animate")],
};
