/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adapters_fetch_fetchWsfScheduledTripsData from "../adapters/fetch/fetchWsfScheduledTripsData.js";
import type * as adapters_fetch_fetchWsfScheduledTripsTypes from "../adapters/fetch/fetchWsfScheduledTripsTypes.js";
import type * as adapters_fetch_fetchWsfTerminalIdentities from "../adapters/fetch/fetchWsfTerminalIdentities.js";
import type * as adapters_fetch_fetchWsfTerminalsAndMates from "../adapters/fetch/fetchWsfTerminalsAndMates.js";
import type * as adapters_fetch_fetchWsfVesselIdentities from "../adapters/fetch/fetchWsfVesselIdentities.js";
import type * as adapters_fetch_fetchWsfVesselLocations from "../adapters/fetch/fetchWsfVesselLocations.js";
import type * as adapters_fetch_fetchWsfVesselPings from "../adapters/fetch/fetchWsfVesselPings.js";
import type * as adapters_index from "../adapters/index.js";
import type * as adapters_pipelines_buildWsfTerminalsTopology from "../adapters/pipelines/buildWsfTerminalsTopology.js";
import type * as adapters_pipelines_createWsfScheduledTripFromRawSegment from "../adapters/pipelines/createWsfScheduledTripFromRawSegment.js";
import type * as adapters_pipelines_fetchWsfScheduledTrips from "../adapters/pipelines/fetchWsfScheduledTrips.js";
import type * as adapters_resolve_resolveWsfScheduleSegment from "../adapters/resolve/resolveWsfScheduleSegment.js";
import type * as adapters_resolve_resolveWsfTerminal from "../adapters/resolve/resolveWsfTerminal.js";
import type * as adapters_resolve_resolveWsfVessel from "../adapters/resolve/resolveWsfVessel.js";
import type * as adapters_resolve_resolveWsfVesselHistory from "../adapters/resolve/resolveWsfVesselHistory.js";
import type * as adapters_utils_retryOnce from "../adapters/utils/retryOnce.js";
import type * as crons from "../crons.js";
import type * as domain_events_actual from "../domain/events/actual.js";
import type * as domain_events_predicted from "../domain/events/predicted.js";
import type * as domain_events_reload_actuals_buildPhysicalOnlyTripActualRows from "../domain/events/reload/actuals/buildPhysicalOnlyTripActualRows.js";
import type * as domain_events_reload_actuals_dedupeActualRows from "../domain/events/reload/actuals/dedupeActualRows.js";
import type * as domain_events_reload_actuals_index from "../domain/events/reload/actuals/index.js";
import type * as domain_events_reload_actuals_mergeHistoryActuals from "../domain/events/reload/actuals/mergeHistoryActuals.js";
import type * as domain_events_reload_actuals_physicalOnlyLiveLocations from "../domain/events/reload/actuals/physicalOnlyLiveLocations.js";
import type * as domain_events_reload_actuals_reconcileLiveLocations from "../domain/events/reload/actuals/reconcileLiveLocations.js";
import type * as domain_events_reload_actuals_scheduleAlignedLiveLocations from "../domain/events/reload/actuals/scheduleAlignedLiveLocations.js";
import type * as domain_events_reload_actuals_utils_buildPhysicalOnlyTripPatch from "../domain/events/reload/actuals/utils/buildPhysicalOnlyTripPatch.js";
import type * as domain_events_reload_actuals_utils_index from "../domain/events/reload/actuals/utils/index.js";
import type * as domain_events_reload_computeDockEventsReload from "../domain/events/reload/computeDockEventsReload.js";
import type * as domain_events_reload_computeReloadRowsFromScheduledEvents from "../domain/events/reload/computeReloadRowsFromScheduledEvents.js";
import type * as domain_events_reload_index from "../domain/events/reload/index.js";
import type * as domain_events_reload_schedule_compareDockEventsByTimeline from "../domain/events/reload/schedule/compareDockEventsByTimeline.js";
import type * as domain_events_reload_schedule_convertAdapterRows from "../domain/events/reload/schedule/convertAdapterRows.js";
import type * as domain_events_reload_schedule_hydrateScheduledEvents from "../domain/events/reload/schedule/hydrateScheduledEvents.js";
import type * as domain_events_reload_schedule_index from "../domain/events/reload/schedule/index.js";
import type * as domain_events_reload_schedule_resolveSeedSegments from "../domain/events/reload/schedule/resolveSeedSegments.js";
import type * as domain_events_reload_schemas_index from "../domain/events/reload/schemas/index.js";
import type * as domain_events_reload_schemas_validateReloadInput from "../domain/events/reload/schemas/validateReloadInput.js";
import type * as domain_events_reload_shared_constants from "../domain/events/reload/shared/constants.js";
import type * as domain_events_reload_shared_groupRows from "../domain/events/reload/shared/groupRows.js";
import type * as domain_events_reload_shared_index from "../domain/events/reload/shared/index.js";
import type * as domain_events_reload_trips_index from "../domain/events/reload/trips/index.js";
import type * as domain_events_reload_trips_indexTripsForReload from "../domain/events/reload/trips/indexTripsForReload.js";
import type * as domain_events_reload_types from "../domain/events/reload/types.js";
import type * as domain_events_scheduled from "../domain/events/scheduled.js";
import type * as domain_index from "../domain/index.js";
import type * as domain_ml_index from "../domain/ml/index.js";
import type * as domain_ml_prediction_applyModel from "../domain/ml/prediction/applyModel.js";
import type * as domain_ml_prediction_index from "../domain/ml/prediction/index.js";
import type * as domain_ml_prediction_metrics from "../domain/ml/prediction/metrics.js";
import type * as domain_ml_prediction_predictTrip from "../domain/ml/prediction/predictTrip.js";
import type * as domain_ml_prediction_vesselTripPredictionModelAccess from "../domain/ml/prediction/vesselTripPredictionModelAccess.js";
import type * as domain_ml_prediction_vesselTripPredictions from "../domain/ml/prediction/vesselTripPredictions.js";
import type * as domain_ml_shared_config from "../domain/ml/shared/config.js";
import type * as domain_ml_shared_featureRecord from "../domain/ml/shared/featureRecord.js";
import type * as domain_ml_shared_features from "../domain/ml/shared/features.js";
import type * as domain_ml_shared_index from "../domain/ml/shared/index.js";
import type * as domain_ml_shared_models from "../domain/ml/shared/models.js";
import type * as domain_ml_shared_types from "../domain/ml/shared/types.js";
import type * as domain_ml_shared_unifiedTrip from "../domain/ml/shared/unifiedTrip.js";
import type * as domain_ml_training_actions from "../domain/ml/training/actions.js";
import type * as domain_ml_training_data_createTrainingBuckets from "../domain/ml/training/data/createTrainingBuckets.js";
import type * as domain_ml_training_data_createTrainingWindows from "../domain/ml/training/data/createTrainingWindows.js";
import type * as domain_ml_training_data_index from "../domain/ml/training/data/index.js";
import type * as domain_ml_training_data_loadTrainingData from "../domain/ml/training/data/loadTrainingData.js";
import type * as domain_ml_training_index from "../domain/ml/training/index.js";
import type * as domain_ml_training_models_index from "../domain/ml/training/models/index.js";
import type * as domain_ml_training_models_storeModels from "../domain/ml/training/models/storeModels.js";
import type * as domain_ml_training_models_trainModels from "../domain/ml/training/models/trainModels.js";
import type * as domain_ml_training_pipeline from "../domain/ml/training/pipeline.js";
import type * as domain_scheduledTrips_applyPrefetchSchedulePolicies from "../domain/scheduledTrips/applyPrefetchSchedulePolicies.js";
import type * as domain_scheduledTrips_buildInitialScheduledTripRow from "../domain/scheduledTrips/buildInitialScheduledTripRow.js";
import type * as domain_scheduledTrips_calculateTripEstimates from "../domain/scheduledTrips/calculateTripEstimates.js";
import type * as domain_scheduledTrips_classifyDirectSegments from "../domain/scheduledTrips/classifyDirectSegments.js";
import type * as domain_scheduledTrips_grouping from "../domain/scheduledTrips/grouping.js";
import type * as domain_scheduledTrips_index from "../domain/scheduledTrips/index.js";
import type * as domain_scheduledTrips_officialCrossingTimes from "../domain/scheduledTrips/officialCrossingTimes.js";
import type * as domain_scheduledTrips_runScheduleTransformPipeline from "../domain/scheduledTrips/runScheduleTransformPipeline.js";
import type * as domain_vesselOrchestration_index from "../domain/vesselOrchestration/index.js";
import type * as domain_vesselOrchestration_updateEvents_actualDockWritesFromTrip from "../domain/vesselOrchestration/updateEvents/actualDockWritesFromTrip.js";
import type * as domain_vesselOrchestration_updateEvents_buildDockWritesFromTripHandoff from "../domain/vesselOrchestration/updateEvents/buildDockWritesFromTripHandoff.js";
import type * as domain_vesselOrchestration_updateEvents_completedHandoffKey from "../domain/vesselOrchestration/updateEvents/completedHandoffKey.js";
import type * as domain_vesselOrchestration_updateEvents_contracts from "../domain/vesselOrchestration/updateEvents/contracts.js";
import type * as domain_vesselOrchestration_updateEvents_eventHandoffFromTripUpdate from "../domain/vesselOrchestration/updateEvents/eventHandoffFromTripUpdate.js";
import type * as domain_vesselOrchestration_updateEvents_eventWriteAssembler from "../domain/vesselOrchestration/updateEvents/eventWriteAssembler.js";
import type * as domain_vesselOrchestration_updateEvents_handoffTypes from "../domain/vesselOrchestration/updateEvents/handoffTypes.js";
import type * as domain_vesselOrchestration_updateEvents_index from "../domain/vesselOrchestration/updateEvents/index.js";
import type * as domain_vesselOrchestration_updateEvents_projectEventsFromHandoff from "../domain/vesselOrchestration/updateEvents/projectEventsFromHandoff.js";
import type * as domain_vesselOrchestration_updateEvents_projectionWire from "../domain/vesselOrchestration/updateEvents/projectionWire.js";
import type * as domain_vesselOrchestration_updateEvents_updateEvents from "../domain/vesselOrchestration/updateEvents/updateEvents.js";
import type * as domain_vesselOrchestration_updateLeaveDockEventPatch_index from "../domain/vesselOrchestration/updateLeaveDockEventPatch/index.js";
import type * as domain_vesselOrchestration_updateLeaveDockEventPatch_updateLeaveDockEventPatch from "../domain/vesselOrchestration/updateLeaveDockEventPatch/updateLeaveDockEventPatch.js";
import type * as domain_vesselOrchestration_updateVesselLocations_addAtDockObserved from "../domain/vesselOrchestration/updateVesselLocations/addAtDockObserved.js";
import type * as domain_vesselOrchestration_updateVesselLocations_contracts from "../domain/vesselOrchestration/updateVesselLocations/contracts.js";
import type * as domain_vesselOrchestration_updateVesselLocations_index from "../domain/vesselOrchestration/updateVesselLocations/index.js";
import type * as domain_vesselOrchestration_updateVesselLocations_mapWsfVesselLocations from "../domain/vesselOrchestration/updateVesselLocations/mapWsfVesselLocations.js";
import type * as domain_vesselOrchestration_updateVesselLocations_updateVesselLocations from "../domain/vesselOrchestration/updateVesselLocations/updateVesselLocations.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_appendPredictions from "../domain/vesselOrchestration/updateVesselPredictions/appendPredictions.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_applyVesselPredictions from "../domain/vesselOrchestration/updateVesselPredictions/applyVesselPredictions.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_getPredictionModelParametersFromTripUpdate from "../domain/vesselOrchestration/updateVesselPredictions/getPredictionModelParametersFromTripUpdate.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_getVesselTripPredictionsFromTripUpdate from "../domain/vesselOrchestration/updateVesselPredictions/getVesselTripPredictionsFromTripUpdate.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_index from "../domain/vesselOrchestration/updateVesselPredictions/index.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_tripDockStatePredictionSpecs from "../domain/vesselOrchestration/updateVesselPredictions/tripDockStatePredictionSpecs.js";
import type * as domain_vesselOrchestration_updateVesselPredictions_types from "../domain/vesselOrchestration/updateVesselPredictions/types.js";
import type * as domain_vesselOrchestration_updateVesselTrip_comparison_isSameVesselTripData from "../domain/vesselOrchestration/updateVesselTrip/comparison/isSameVesselTripData.js";
import type * as domain_vesselOrchestration_updateVesselTrip_comparison_stripTripPredictionsForStorage from "../domain/vesselOrchestration/updateVesselTrip/comparison/stripTripPredictionsForStorage.js";
import type * as domain_vesselOrchestration_updateVesselTrip_dockTransitionEvents from "../domain/vesselOrchestration/updateVesselTrip/dockTransitionEvents.js";
import type * as domain_vesselOrchestration_updateVesselTrip_index from "../domain/vesselOrchestration/updateVesselTrip/index.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_applyScheduleToActiveTrip from "../domain/vesselOrchestration/updateVesselTrip/schedule/applyScheduleToActiveTrip.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_index from "../domain/vesselOrchestration/updateVesselTrip/schedule/index.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_mapScheduledSegmentToTripScheduleResolution from "../domain/vesselOrchestration/updateVesselTrip/schedule/mapScheduledSegmentToTripScheduleResolution.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_mergeScheduleResolutionIntoTrip from "../domain/vesselOrchestration/updateVesselTrip/schedule/mergeScheduleResolutionIntoTrip.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleForActiveTrip from "../domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleForActiveTrip.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromNextScheduleKey from "../domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromNextScheduleKey.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromScheduledTripsDb from "../domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromScheduledTripsDb.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromWsfRealtimeFields from "../domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromWsfRealtimeFields.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_tests_testHelpers from "../domain/vesselOrchestration/updateVesselTrip/schedule/tests/testHelpers.js";
import type * as domain_vesselOrchestration_updateVesselTrip_schedule_types from "../domain/vesselOrchestration/updateVesselTrip/schedule/types.js";
import type * as domain_vesselOrchestration_updateVesselTrip_tripRows_buildActiveTrip from "../domain/vesselOrchestration/updateVesselTrip/tripRows/buildActiveTrip.js";
import type * as domain_vesselOrchestration_updateVesselTrip_tripRows_buildCompleteTrip from "../domain/vesselOrchestration/updateVesselTrip/tripRows/buildCompleteTrip.js";
import type * as domain_vesselOrchestration_updateVesselTrip_types from "../domain/vesselOrchestration/updateVesselTrip/types.js";
import type * as domain_vesselOrchestration_updateVesselTrip_updateVesselTrip from "../domain/vesselOrchestration/updateVesselTrip/updateVesselTrip.js";
import type * as functions_events_common_schemas from "../functions/events/common/schemas.js";
import type * as functions_events_eventsActual_index from "../functions/events/eventsActual/index.js";
import type * as functions_events_eventsActual_mutations from "../functions/events/eventsActual/mutations.js";
import type * as functions_events_eventsActual_queries from "../functions/events/eventsActual/queries.js";
import type * as functions_events_eventsActual_schemas from "../functions/events/eventsActual/schemas.js";
import type * as functions_events_eventsPredicted_index from "../functions/events/eventsPredicted/index.js";
import type * as functions_events_eventsPredicted_mutations from "../functions/events/eventsPredicted/mutations.js";
import type * as functions_events_eventsPredicted_queries from "../functions/events/eventsPredicted/queries.js";
import type * as functions_events_eventsPredicted_schemas from "../functions/events/eventsPredicted/schemas.js";
import type * as functions_events_eventsScheduled_index from "../functions/events/eventsScheduled/index.js";
import type * as functions_events_eventsScheduled_mutations from "../functions/events/eventsScheduled/mutations.js";
import type * as functions_events_eventsScheduled_queries from "../functions/events/eventsScheduled/queries.js";
import type * as functions_events_eventsScheduled_schemas from "../functions/events/eventsScheduled/schemas.js";
import type * as functions_events_index from "../functions/events/index.js";
import type * as functions_events_reload_actions from "../functions/events/reload/actions.js";
import type * as functions_events_reload_index from "../functions/events/reload/index.js";
import type * as functions_events_reload_mutations from "../functions/events/reload/mutations.js";
import type * as functions_events_reload_reloadDockEventsForSailingDay from "../functions/events/reload/reloadDockEventsForSailingDay.js";
import type * as functions_events_reload_reloadDockEventsWindow from "../functions/events/reload/reloadDockEventsWindow.js";
import type * as functions_events_reload_reloadDockInputs from "../functions/events/reload/reloadDockInputs.js";
import type * as functions_index from "../functions/index.js";
import type * as functions_keyValueStore_helpers from "../functions/keyValueStore/helpers.js";
import type * as functions_keyValueStore_index from "../functions/keyValueStore/index.js";
import type * as functions_keyValueStore_mutations from "../functions/keyValueStore/mutations.js";
import type * as functions_keyValueStore_queries from "../functions/keyValueStore/queries.js";
import type * as functions_keyValueStore_schemas from "../functions/keyValueStore/schemas.js";
import type * as functions_predictions_index from "../functions/predictions/index.js";
import type * as functions_predictions_mutations from "../functions/predictions/mutations.js";
import type * as functions_predictions_queries from "../functions/predictions/queries.js";
import type * as functions_predictions_schemas from "../functions/predictions/schemas.js";
import type * as functions_scheduledTrips_actions from "../functions/scheduledTrips/actions.js";
import type * as functions_scheduledTrips_constants from "../functions/scheduledTrips/constants.js";
import type * as functions_scheduledTrips_index from "../functions/scheduledTrips/index.js";
import type * as functions_scheduledTrips_mutations from "../functions/scheduledTrips/mutations.js";
import type * as functions_scheduledTrips_queries from "../functions/scheduledTrips/queries.js";
import type * as functions_scheduledTrips_schemas from "../functions/scheduledTrips/schemas.js";
import type * as functions_scheduledTrips_sync from "../functions/scheduledTrips/sync.js";
import type * as functions_scheduledTrips_types from "../functions/scheduledTrips/types.js";
import type * as functions_terminals_actions from "../functions/terminals/actions.js";
import type * as functions_terminals_mutations from "../functions/terminals/mutations.js";
import type * as functions_terminals_queries from "../functions/terminals/queries.js";
import type * as functions_terminals_schemas from "../functions/terminals/schemas.js";
import type * as functions_terminalsTopology_actions from "../functions/terminalsTopology/actions.js";
import type * as functions_terminalsTopology_mutations from "../functions/terminalsTopology/mutations.js";
import type * as functions_terminalsTopology_queries from "../functions/terminalsTopology/queries.js";
import type * as functions_terminalsTopology_schemas from "../functions/terminalsTopology/schemas.js";
import type * as functions_vesselLocation_index from "../functions/vesselLocation/index.js";
import type * as functions_vesselLocation_mutations from "../functions/vesselLocation/mutations.js";
import type * as functions_vesselLocation_queries from "../functions/vesselLocation/queries.js";
import type * as functions_vesselLocation_schemas from "../functions/vesselLocation/schemas.js";
import type * as functions_vesselLocation_types from "../functions/vesselLocation/types.js";
import type * as functions_vesselLocationsHistoric_actions from "../functions/vesselLocationsHistoric/actions.js";
import type * as functions_vesselLocationsHistoric_index from "../functions/vesselLocationsHistoric/index.js";
import type * as functions_vesselLocationsHistoric_mutations from "../functions/vesselLocationsHistoric/mutations.js";
import type * as functions_vesselLocationsHistoric_queries from "../functions/vesselLocationsHistoric/queries.js";
import type * as functions_vesselLocationsHistoric_schemas from "../functions/vesselLocationsHistoric/schemas.js";
import type * as functions_vesselOrchestrator_actions_index from "../functions/vesselOrchestrator/actions/index.js";
import type * as functions_vesselOrchestrator_actions_ping_loadSnapshot_index from "../functions/vesselOrchestrator/actions/ping/loadSnapshot/index.js";
import type * as functions_vesselOrchestrator_actions_ping_loadSnapshot_loadSnapshot from "../functions/vesselOrchestrator/actions/ping/loadSnapshot/loadSnapshot.js";
import type * as functions_vesselOrchestrator_actions_ping_runOrchestratorPing from "../functions/vesselOrchestrator/actions/ping/runOrchestratorPing.js";
import type * as functions_vesselOrchestrator_actions_ping_runPersistVesselUpdatesWithTripDeltas from "../functions/vesselOrchestrator/actions/ping/runPersistVesselUpdatesWithTripDeltas.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselLocations_index from "../functions/vesselOrchestrator/actions/ping/updateVesselLocations/index.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselLocations_persist from "../functions/vesselOrchestrator/actions/ping/updateVesselLocations/persist.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselLocations_run from "../functions/vesselOrchestrator/actions/ping/updateVesselLocations/run.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselPredictions_getVesselTripPredictionsForTripUpdate from "../functions/vesselOrchestrator/actions/ping/updateVesselPredictions/getVesselTripPredictionsForTripUpdate.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselPredictions_index from "../functions/vesselOrchestrator/actions/ping/updateVesselPredictions/index.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselPredictions_load from "../functions/vesselOrchestrator/actions/ping/updateVesselPredictions/load.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselTrip_index from "../functions/vesselOrchestrator/actions/ping/updateVesselTrip/index.js";
import type * as functions_vesselOrchestrator_actions_ping_updateVesselTrip_updateVesselTripDbAccess from "../functions/vesselOrchestrator/actions/ping/updateVesselTrip/updateVesselTripDbAccess.js";
import type * as functions_vesselOrchestrator_actions_updateVesselOrchestrator from "../functions/vesselOrchestrator/actions/updateVesselOrchestrator.js";
import type * as functions_vesselOrchestrator_index from "../functions/vesselOrchestrator/index.js";
import type * as functions_vesselOrchestrator_mutations_index from "../functions/vesselOrchestrator/mutations/index.js";
import type * as functions_vesselOrchestrator_mutations_orchestratorPersistMutations from "../functions/vesselOrchestrator/mutations/orchestratorPersistMutations.js";
import type * as functions_vesselOrchestrator_queries_index from "../functions/vesselOrchestrator/queries/index.js";
import type * as functions_vesselOrchestrator_queries_orchestratorSnapshotQueries from "../functions/vesselOrchestrator/queries/orchestratorSnapshotQueries.js";
import type * as functions_vesselOrchestrator_queries_vesselTripScheduleQueries from "../functions/vesselOrchestrator/queries/vesselTripScheduleQueries.js";
import type * as functions_vesselPings_actions from "../functions/vesselPings/actions.js";
import type * as functions_vesselPings_index from "../functions/vesselPings/index.js";
import type * as functions_vesselPings_mutations from "../functions/vesselPings/mutations.js";
import type * as functions_vesselPings_queries from "../functions/vesselPings/queries.js";
import type * as functions_vesselPings_schemas from "../functions/vesselPings/schemas.js";
import type * as functions_vesselPings_types from "../functions/vesselPings/types.js";
import type * as functions_vesselTrips_columnAudit from "../functions/vesselTrips/columnAudit.js";
import type * as functions_vesselTrips_index from "../functions/vesselTrips/index.js";
import type * as functions_vesselTrips_mutations from "../functions/vesselTrips/mutations.js";
import type * as functions_vesselTrips_queries from "../functions/vesselTrips/queries.js";
import type * as functions_vesselTrips_read_dedupeTripDocsByTripKey from "../functions/vesselTrips/read/dedupeTripDocsByTripKey.js";
import type * as functions_vesselTrips_read_index from "../functions/vesselTrips/read/index.js";
import type * as functions_vesselTrips_read_mergeTripsWithPredictions from "../functions/vesselTrips/read/mergeTripsWithPredictions.js";
import type * as functions_vesselTrips_schemas from "../functions/vesselTrips/schemas.js";
import type * as functions_vesselTrips_types from "../functions/vesselTrips/types.js";
import type * as functions_vessels_actions from "../functions/vessels/actions.js";
import type * as functions_vessels_schemas from "../functions/vessels/schemas.js";
import type * as shared_convertDates from "../shared/convertDates.js";
import type * as shared_deepEqual from "../shared/deepEqual.js";
import type * as shared_distanceUtils from "../shared/distanceUtils.js";
import type * as shared_durationUtils from "../shared/durationUtils.js";
import type * as shared_groupBy from "../shared/groupBy.js";
import type * as shared_index from "../shared/index.js";
import type * as shared_keys from "../shared/keys.js";
import type * as shared_physicalTripIdentity from "../shared/physicalTripIdentity.js";
import type * as shared_stripConvexMeta from "../shared/stripConvexMeta.js";
import type * as shared_time from "../shared/time.js";
import type * as shared_tripIdentity from "../shared/tripIdentity.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "adapters/fetch/fetchWsfScheduledTripsData": typeof adapters_fetch_fetchWsfScheduledTripsData;
  "adapters/fetch/fetchWsfScheduledTripsTypes": typeof adapters_fetch_fetchWsfScheduledTripsTypes;
  "adapters/fetch/fetchWsfTerminalIdentities": typeof adapters_fetch_fetchWsfTerminalIdentities;
  "adapters/fetch/fetchWsfTerminalsAndMates": typeof adapters_fetch_fetchWsfTerminalsAndMates;
  "adapters/fetch/fetchWsfVesselIdentities": typeof adapters_fetch_fetchWsfVesselIdentities;
  "adapters/fetch/fetchWsfVesselLocations": typeof adapters_fetch_fetchWsfVesselLocations;
  "adapters/fetch/fetchWsfVesselPings": typeof adapters_fetch_fetchWsfVesselPings;
  "adapters/index": typeof adapters_index;
  "adapters/pipelines/buildWsfTerminalsTopology": typeof adapters_pipelines_buildWsfTerminalsTopology;
  "adapters/pipelines/createWsfScheduledTripFromRawSegment": typeof adapters_pipelines_createWsfScheduledTripFromRawSegment;
  "adapters/pipelines/fetchWsfScheduledTrips": typeof adapters_pipelines_fetchWsfScheduledTrips;
  "adapters/resolve/resolveWsfScheduleSegment": typeof adapters_resolve_resolveWsfScheduleSegment;
  "adapters/resolve/resolveWsfTerminal": typeof adapters_resolve_resolveWsfTerminal;
  "adapters/resolve/resolveWsfVessel": typeof adapters_resolve_resolveWsfVessel;
  "adapters/resolve/resolveWsfVesselHistory": typeof adapters_resolve_resolveWsfVesselHistory;
  "adapters/utils/retryOnce": typeof adapters_utils_retryOnce;
  crons: typeof crons;
  "domain/events/actual": typeof domain_events_actual;
  "domain/events/predicted": typeof domain_events_predicted;
  "domain/events/reload/actuals/buildPhysicalOnlyTripActualRows": typeof domain_events_reload_actuals_buildPhysicalOnlyTripActualRows;
  "domain/events/reload/actuals/dedupeActualRows": typeof domain_events_reload_actuals_dedupeActualRows;
  "domain/events/reload/actuals/index": typeof domain_events_reload_actuals_index;
  "domain/events/reload/actuals/mergeHistoryActuals": typeof domain_events_reload_actuals_mergeHistoryActuals;
  "domain/events/reload/actuals/physicalOnlyLiveLocations": typeof domain_events_reload_actuals_physicalOnlyLiveLocations;
  "domain/events/reload/actuals/reconcileLiveLocations": typeof domain_events_reload_actuals_reconcileLiveLocations;
  "domain/events/reload/actuals/scheduleAlignedLiveLocations": typeof domain_events_reload_actuals_scheduleAlignedLiveLocations;
  "domain/events/reload/actuals/utils/buildPhysicalOnlyTripPatch": typeof domain_events_reload_actuals_utils_buildPhysicalOnlyTripPatch;
  "domain/events/reload/actuals/utils/index": typeof domain_events_reload_actuals_utils_index;
  "domain/events/reload/computeDockEventsReload": typeof domain_events_reload_computeDockEventsReload;
  "domain/events/reload/computeReloadRowsFromScheduledEvents": typeof domain_events_reload_computeReloadRowsFromScheduledEvents;
  "domain/events/reload/index": typeof domain_events_reload_index;
  "domain/events/reload/schedule/compareDockEventsByTimeline": typeof domain_events_reload_schedule_compareDockEventsByTimeline;
  "domain/events/reload/schedule/convertAdapterRows": typeof domain_events_reload_schedule_convertAdapterRows;
  "domain/events/reload/schedule/hydrateScheduledEvents": typeof domain_events_reload_schedule_hydrateScheduledEvents;
  "domain/events/reload/schedule/index": typeof domain_events_reload_schedule_index;
  "domain/events/reload/schedule/resolveSeedSegments": typeof domain_events_reload_schedule_resolveSeedSegments;
  "domain/events/reload/schemas/index": typeof domain_events_reload_schemas_index;
  "domain/events/reload/schemas/validateReloadInput": typeof domain_events_reload_schemas_validateReloadInput;
  "domain/events/reload/shared/constants": typeof domain_events_reload_shared_constants;
  "domain/events/reload/shared/groupRows": typeof domain_events_reload_shared_groupRows;
  "domain/events/reload/shared/index": typeof domain_events_reload_shared_index;
  "domain/events/reload/trips/index": typeof domain_events_reload_trips_index;
  "domain/events/reload/trips/indexTripsForReload": typeof domain_events_reload_trips_indexTripsForReload;
  "domain/events/reload/types": typeof domain_events_reload_types;
  "domain/events/scheduled": typeof domain_events_scheduled;
  "domain/index": typeof domain_index;
  "domain/ml/index": typeof domain_ml_index;
  "domain/ml/prediction/applyModel": typeof domain_ml_prediction_applyModel;
  "domain/ml/prediction/index": typeof domain_ml_prediction_index;
  "domain/ml/prediction/metrics": typeof domain_ml_prediction_metrics;
  "domain/ml/prediction/predictTrip": typeof domain_ml_prediction_predictTrip;
  "domain/ml/prediction/vesselTripPredictionModelAccess": typeof domain_ml_prediction_vesselTripPredictionModelAccess;
  "domain/ml/prediction/vesselTripPredictions": typeof domain_ml_prediction_vesselTripPredictions;
  "domain/ml/shared/config": typeof domain_ml_shared_config;
  "domain/ml/shared/featureRecord": typeof domain_ml_shared_featureRecord;
  "domain/ml/shared/features": typeof domain_ml_shared_features;
  "domain/ml/shared/index": typeof domain_ml_shared_index;
  "domain/ml/shared/models": typeof domain_ml_shared_models;
  "domain/ml/shared/types": typeof domain_ml_shared_types;
  "domain/ml/shared/unifiedTrip": typeof domain_ml_shared_unifiedTrip;
  "domain/ml/training/actions": typeof domain_ml_training_actions;
  "domain/ml/training/data/createTrainingBuckets": typeof domain_ml_training_data_createTrainingBuckets;
  "domain/ml/training/data/createTrainingWindows": typeof domain_ml_training_data_createTrainingWindows;
  "domain/ml/training/data/index": typeof domain_ml_training_data_index;
  "domain/ml/training/data/loadTrainingData": typeof domain_ml_training_data_loadTrainingData;
  "domain/ml/training/index": typeof domain_ml_training_index;
  "domain/ml/training/models/index": typeof domain_ml_training_models_index;
  "domain/ml/training/models/storeModels": typeof domain_ml_training_models_storeModels;
  "domain/ml/training/models/trainModels": typeof domain_ml_training_models_trainModels;
  "domain/ml/training/pipeline": typeof domain_ml_training_pipeline;
  "domain/scheduledTrips/applyPrefetchSchedulePolicies": typeof domain_scheduledTrips_applyPrefetchSchedulePolicies;
  "domain/scheduledTrips/buildInitialScheduledTripRow": typeof domain_scheduledTrips_buildInitialScheduledTripRow;
  "domain/scheduledTrips/calculateTripEstimates": typeof domain_scheduledTrips_calculateTripEstimates;
  "domain/scheduledTrips/classifyDirectSegments": typeof domain_scheduledTrips_classifyDirectSegments;
  "domain/scheduledTrips/grouping": typeof domain_scheduledTrips_grouping;
  "domain/scheduledTrips/index": typeof domain_scheduledTrips_index;
  "domain/scheduledTrips/officialCrossingTimes": typeof domain_scheduledTrips_officialCrossingTimes;
  "domain/scheduledTrips/runScheduleTransformPipeline": typeof domain_scheduledTrips_runScheduleTransformPipeline;
  "domain/vesselOrchestration/index": typeof domain_vesselOrchestration_index;
  "domain/vesselOrchestration/updateEvents/actualDockWritesFromTrip": typeof domain_vesselOrchestration_updateEvents_actualDockWritesFromTrip;
  "domain/vesselOrchestration/updateEvents/buildDockWritesFromTripHandoff": typeof domain_vesselOrchestration_updateEvents_buildDockWritesFromTripHandoff;
  "domain/vesselOrchestration/updateEvents/completedHandoffKey": typeof domain_vesselOrchestration_updateEvents_completedHandoffKey;
  "domain/vesselOrchestration/updateEvents/contracts": typeof domain_vesselOrchestration_updateEvents_contracts;
  "domain/vesselOrchestration/updateEvents/eventHandoffFromTripUpdate": typeof domain_vesselOrchestration_updateEvents_eventHandoffFromTripUpdate;
  "domain/vesselOrchestration/updateEvents/eventWriteAssembler": typeof domain_vesselOrchestration_updateEvents_eventWriteAssembler;
  "domain/vesselOrchestration/updateEvents/handoffTypes": typeof domain_vesselOrchestration_updateEvents_handoffTypes;
  "domain/vesselOrchestration/updateEvents/index": typeof domain_vesselOrchestration_updateEvents_index;
  "domain/vesselOrchestration/updateEvents/projectEventsFromHandoff": typeof domain_vesselOrchestration_updateEvents_projectEventsFromHandoff;
  "domain/vesselOrchestration/updateEvents/projectionWire": typeof domain_vesselOrchestration_updateEvents_projectionWire;
  "domain/vesselOrchestration/updateEvents/updateEvents": typeof domain_vesselOrchestration_updateEvents_updateEvents;
  "domain/vesselOrchestration/updateLeaveDockEventPatch/index": typeof domain_vesselOrchestration_updateLeaveDockEventPatch_index;
  "domain/vesselOrchestration/updateLeaveDockEventPatch/updateLeaveDockEventPatch": typeof domain_vesselOrchestration_updateLeaveDockEventPatch_updateLeaveDockEventPatch;
  "domain/vesselOrchestration/updateVesselLocations/addAtDockObserved": typeof domain_vesselOrchestration_updateVesselLocations_addAtDockObserved;
  "domain/vesselOrchestration/updateVesselLocations/contracts": typeof domain_vesselOrchestration_updateVesselLocations_contracts;
  "domain/vesselOrchestration/updateVesselLocations/index": typeof domain_vesselOrchestration_updateVesselLocations_index;
  "domain/vesselOrchestration/updateVesselLocations/mapWsfVesselLocations": typeof domain_vesselOrchestration_updateVesselLocations_mapWsfVesselLocations;
  "domain/vesselOrchestration/updateVesselLocations/updateVesselLocations": typeof domain_vesselOrchestration_updateVesselLocations_updateVesselLocations;
  "domain/vesselOrchestration/updateVesselPredictions/appendPredictions": typeof domain_vesselOrchestration_updateVesselPredictions_appendPredictions;
  "domain/vesselOrchestration/updateVesselPredictions/applyVesselPredictions": typeof domain_vesselOrchestration_updateVesselPredictions_applyVesselPredictions;
  "domain/vesselOrchestration/updateVesselPredictions/getPredictionModelParametersFromTripUpdate": typeof domain_vesselOrchestration_updateVesselPredictions_getPredictionModelParametersFromTripUpdate;
  "domain/vesselOrchestration/updateVesselPredictions/getVesselTripPredictionsFromTripUpdate": typeof domain_vesselOrchestration_updateVesselPredictions_getVesselTripPredictionsFromTripUpdate;
  "domain/vesselOrchestration/updateVesselPredictions/index": typeof domain_vesselOrchestration_updateVesselPredictions_index;
  "domain/vesselOrchestration/updateVesselPredictions/tripDockStatePredictionSpecs": typeof domain_vesselOrchestration_updateVesselPredictions_tripDockStatePredictionSpecs;
  "domain/vesselOrchestration/updateVesselPredictions/types": typeof domain_vesselOrchestration_updateVesselPredictions_types;
  "domain/vesselOrchestration/updateVesselTrip/comparison/isSameVesselTripData": typeof domain_vesselOrchestration_updateVesselTrip_comparison_isSameVesselTripData;
  "domain/vesselOrchestration/updateVesselTrip/comparison/stripTripPredictionsForStorage": typeof domain_vesselOrchestration_updateVesselTrip_comparison_stripTripPredictionsForStorage;
  "domain/vesselOrchestration/updateVesselTrip/dockTransitionEvents": typeof domain_vesselOrchestration_updateVesselTrip_dockTransitionEvents;
  "domain/vesselOrchestration/updateVesselTrip/index": typeof domain_vesselOrchestration_updateVesselTrip_index;
  "domain/vesselOrchestration/updateVesselTrip/schedule/applyScheduleToActiveTrip": typeof domain_vesselOrchestration_updateVesselTrip_schedule_applyScheduleToActiveTrip;
  "domain/vesselOrchestration/updateVesselTrip/schedule/index": typeof domain_vesselOrchestration_updateVesselTrip_schedule_index;
  "domain/vesselOrchestration/updateVesselTrip/schedule/mapScheduledSegmentToTripScheduleResolution": typeof domain_vesselOrchestration_updateVesselTrip_schedule_mapScheduledSegmentToTripScheduleResolution;
  "domain/vesselOrchestration/updateVesselTrip/schedule/mergeScheduleResolutionIntoTrip": typeof domain_vesselOrchestration_updateVesselTrip_schedule_mergeScheduleResolutionIntoTrip;
  "domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleForActiveTrip": typeof domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleForActiveTrip;
  "domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromNextScheduleKey": typeof domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromNextScheduleKey;
  "domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromScheduledTripsDb": typeof domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromScheduledTripsDb;
  "domain/vesselOrchestration/updateVesselTrip/schedule/resolveScheduleFromWsfRealtimeFields": typeof domain_vesselOrchestration_updateVesselTrip_schedule_resolveScheduleFromWsfRealtimeFields;
  "domain/vesselOrchestration/updateVesselTrip/schedule/tests/testHelpers": typeof domain_vesselOrchestration_updateVesselTrip_schedule_tests_testHelpers;
  "domain/vesselOrchestration/updateVesselTrip/schedule/types": typeof domain_vesselOrchestration_updateVesselTrip_schedule_types;
  "domain/vesselOrchestration/updateVesselTrip/tripRows/buildActiveTrip": typeof domain_vesselOrchestration_updateVesselTrip_tripRows_buildActiveTrip;
  "domain/vesselOrchestration/updateVesselTrip/tripRows/buildCompleteTrip": typeof domain_vesselOrchestration_updateVesselTrip_tripRows_buildCompleteTrip;
  "domain/vesselOrchestration/updateVesselTrip/types": typeof domain_vesselOrchestration_updateVesselTrip_types;
  "domain/vesselOrchestration/updateVesselTrip/updateVesselTrip": typeof domain_vesselOrchestration_updateVesselTrip_updateVesselTrip;
  "functions/events/common/schemas": typeof functions_events_common_schemas;
  "functions/events/eventsActual/index": typeof functions_events_eventsActual_index;
  "functions/events/eventsActual/mutations": typeof functions_events_eventsActual_mutations;
  "functions/events/eventsActual/queries": typeof functions_events_eventsActual_queries;
  "functions/events/eventsActual/schemas": typeof functions_events_eventsActual_schemas;
  "functions/events/eventsPredicted/index": typeof functions_events_eventsPredicted_index;
  "functions/events/eventsPredicted/mutations": typeof functions_events_eventsPredicted_mutations;
  "functions/events/eventsPredicted/queries": typeof functions_events_eventsPredicted_queries;
  "functions/events/eventsPredicted/schemas": typeof functions_events_eventsPredicted_schemas;
  "functions/events/eventsScheduled/index": typeof functions_events_eventsScheduled_index;
  "functions/events/eventsScheduled/mutations": typeof functions_events_eventsScheduled_mutations;
  "functions/events/eventsScheduled/queries": typeof functions_events_eventsScheduled_queries;
  "functions/events/eventsScheduled/schemas": typeof functions_events_eventsScheduled_schemas;
  "functions/events/index": typeof functions_events_index;
  "functions/events/reload/actions": typeof functions_events_reload_actions;
  "functions/events/reload/index": typeof functions_events_reload_index;
  "functions/events/reload/mutations": typeof functions_events_reload_mutations;
  "functions/events/reload/reloadDockEventsForSailingDay": typeof functions_events_reload_reloadDockEventsForSailingDay;
  "functions/events/reload/reloadDockEventsWindow": typeof functions_events_reload_reloadDockEventsWindow;
  "functions/events/reload/reloadDockInputs": typeof functions_events_reload_reloadDockInputs;
  "functions/index": typeof functions_index;
  "functions/keyValueStore/helpers": typeof functions_keyValueStore_helpers;
  "functions/keyValueStore/index": typeof functions_keyValueStore_index;
  "functions/keyValueStore/mutations": typeof functions_keyValueStore_mutations;
  "functions/keyValueStore/queries": typeof functions_keyValueStore_queries;
  "functions/keyValueStore/schemas": typeof functions_keyValueStore_schemas;
  "functions/predictions/index": typeof functions_predictions_index;
  "functions/predictions/mutations": typeof functions_predictions_mutations;
  "functions/predictions/queries": typeof functions_predictions_queries;
  "functions/predictions/schemas": typeof functions_predictions_schemas;
  "functions/scheduledTrips/actions": typeof functions_scheduledTrips_actions;
  "functions/scheduledTrips/constants": typeof functions_scheduledTrips_constants;
  "functions/scheduledTrips/index": typeof functions_scheduledTrips_index;
  "functions/scheduledTrips/mutations": typeof functions_scheduledTrips_mutations;
  "functions/scheduledTrips/queries": typeof functions_scheduledTrips_queries;
  "functions/scheduledTrips/schemas": typeof functions_scheduledTrips_schemas;
  "functions/scheduledTrips/sync": typeof functions_scheduledTrips_sync;
  "functions/scheduledTrips/types": typeof functions_scheduledTrips_types;
  "functions/terminals/actions": typeof functions_terminals_actions;
  "functions/terminals/mutations": typeof functions_terminals_mutations;
  "functions/terminals/queries": typeof functions_terminals_queries;
  "functions/terminals/schemas": typeof functions_terminals_schemas;
  "functions/terminalsTopology/actions": typeof functions_terminalsTopology_actions;
  "functions/terminalsTopology/mutations": typeof functions_terminalsTopology_mutations;
  "functions/terminalsTopology/queries": typeof functions_terminalsTopology_queries;
  "functions/terminalsTopology/schemas": typeof functions_terminalsTopology_schemas;
  "functions/vesselLocation/index": typeof functions_vesselLocation_index;
  "functions/vesselLocation/mutations": typeof functions_vesselLocation_mutations;
  "functions/vesselLocation/queries": typeof functions_vesselLocation_queries;
  "functions/vesselLocation/schemas": typeof functions_vesselLocation_schemas;
  "functions/vesselLocation/types": typeof functions_vesselLocation_types;
  "functions/vesselLocationsHistoric/actions": typeof functions_vesselLocationsHistoric_actions;
  "functions/vesselLocationsHistoric/index": typeof functions_vesselLocationsHistoric_index;
  "functions/vesselLocationsHistoric/mutations": typeof functions_vesselLocationsHistoric_mutations;
  "functions/vesselLocationsHistoric/queries": typeof functions_vesselLocationsHistoric_queries;
  "functions/vesselLocationsHistoric/schemas": typeof functions_vesselLocationsHistoric_schemas;
  "functions/vesselOrchestrator/actions/index": typeof functions_vesselOrchestrator_actions_index;
  "functions/vesselOrchestrator/actions/ping/loadSnapshot/index": typeof functions_vesselOrchestrator_actions_ping_loadSnapshot_index;
  "functions/vesselOrchestrator/actions/ping/loadSnapshot/loadSnapshot": typeof functions_vesselOrchestrator_actions_ping_loadSnapshot_loadSnapshot;
  "functions/vesselOrchestrator/actions/ping/runOrchestratorPing": typeof functions_vesselOrchestrator_actions_ping_runOrchestratorPing;
  "functions/vesselOrchestrator/actions/ping/runPersistVesselUpdatesWithTripDeltas": typeof functions_vesselOrchestrator_actions_ping_runPersistVesselUpdatesWithTripDeltas;
  "functions/vesselOrchestrator/actions/ping/updateVesselLocations/index": typeof functions_vesselOrchestrator_actions_ping_updateVesselLocations_index;
  "functions/vesselOrchestrator/actions/ping/updateVesselLocations/persist": typeof functions_vesselOrchestrator_actions_ping_updateVesselLocations_persist;
  "functions/vesselOrchestrator/actions/ping/updateVesselLocations/run": typeof functions_vesselOrchestrator_actions_ping_updateVesselLocations_run;
  "functions/vesselOrchestrator/actions/ping/updateVesselPredictions/getVesselTripPredictionsForTripUpdate": typeof functions_vesselOrchestrator_actions_ping_updateVesselPredictions_getVesselTripPredictionsForTripUpdate;
  "functions/vesselOrchestrator/actions/ping/updateVesselPredictions/index": typeof functions_vesselOrchestrator_actions_ping_updateVesselPredictions_index;
  "functions/vesselOrchestrator/actions/ping/updateVesselPredictions/load": typeof functions_vesselOrchestrator_actions_ping_updateVesselPredictions_load;
  "functions/vesselOrchestrator/actions/ping/updateVesselTrip/index": typeof functions_vesselOrchestrator_actions_ping_updateVesselTrip_index;
  "functions/vesselOrchestrator/actions/ping/updateVesselTrip/updateVesselTripDbAccess": typeof functions_vesselOrchestrator_actions_ping_updateVesselTrip_updateVesselTripDbAccess;
  "functions/vesselOrchestrator/actions/updateVesselOrchestrator": typeof functions_vesselOrchestrator_actions_updateVesselOrchestrator;
  "functions/vesselOrchestrator/index": typeof functions_vesselOrchestrator_index;
  "functions/vesselOrchestrator/mutations/index": typeof functions_vesselOrchestrator_mutations_index;
  "functions/vesselOrchestrator/mutations/orchestratorPersistMutations": typeof functions_vesselOrchestrator_mutations_orchestratorPersistMutations;
  "functions/vesselOrchestrator/queries/index": typeof functions_vesselOrchestrator_queries_index;
  "functions/vesselOrchestrator/queries/orchestratorSnapshotQueries": typeof functions_vesselOrchestrator_queries_orchestratorSnapshotQueries;
  "functions/vesselOrchestrator/queries/vesselTripScheduleQueries": typeof functions_vesselOrchestrator_queries_vesselTripScheduleQueries;
  "functions/vesselPings/actions": typeof functions_vesselPings_actions;
  "functions/vesselPings/index": typeof functions_vesselPings_index;
  "functions/vesselPings/mutations": typeof functions_vesselPings_mutations;
  "functions/vesselPings/queries": typeof functions_vesselPings_queries;
  "functions/vesselPings/schemas": typeof functions_vesselPings_schemas;
  "functions/vesselPings/types": typeof functions_vesselPings_types;
  "functions/vesselTrips/columnAudit": typeof functions_vesselTrips_columnAudit;
  "functions/vesselTrips/index": typeof functions_vesselTrips_index;
  "functions/vesselTrips/mutations": typeof functions_vesselTrips_mutations;
  "functions/vesselTrips/queries": typeof functions_vesselTrips_queries;
  "functions/vesselTrips/read/dedupeTripDocsByTripKey": typeof functions_vesselTrips_read_dedupeTripDocsByTripKey;
  "functions/vesselTrips/read/index": typeof functions_vesselTrips_read_index;
  "functions/vesselTrips/read/mergeTripsWithPredictions": typeof functions_vesselTrips_read_mergeTripsWithPredictions;
  "functions/vesselTrips/schemas": typeof functions_vesselTrips_schemas;
  "functions/vesselTrips/types": typeof functions_vesselTrips_types;
  "functions/vessels/actions": typeof functions_vessels_actions;
  "functions/vessels/schemas": typeof functions_vessels_schemas;
  "shared/convertDates": typeof shared_convertDates;
  "shared/deepEqual": typeof shared_deepEqual;
  "shared/distanceUtils": typeof shared_distanceUtils;
  "shared/durationUtils": typeof shared_durationUtils;
  "shared/groupBy": typeof shared_groupBy;
  "shared/index": typeof shared_index;
  "shared/keys": typeof shared_keys;
  "shared/physicalTripIdentity": typeof shared_physicalTripIdentity;
  "shared/stripConvexMeta": typeof shared_stripConvexMeta;
  "shared/time": typeof shared_time;
  "shared/tripIdentity": typeof shared_tripIdentity;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
