/**
 * Thresholds and tolerances for dock-event reload assembly: scheduled seam
 * deduping and history merge replacement.
 */

const IDENTICAL_SCHEDULED_DOCK_TIME_OFFSET_MS = 5 * 60 * 1000;
const DEPARTURE_ACTUAL_REPLACEMENT_THRESHOLD_MS = 3 * 60 * 1000;
const ARRIVAL_PROXY_REPLACEMENT_THRESHOLD_MS = 2 * 60 * 1000;

export {
  ARRIVAL_PROXY_REPLACEMENT_THRESHOLD_MS,
  DEPARTURE_ACTUAL_REPLACEMENT_THRESHOLD_MS,
  IDENTICAL_SCHEDULED_DOCK_TIME_OFFSET_MS,
};
