/**
 * Terminal Connections Static Data
 *
 * Complete list of all known terminal connections (terminals and mates).
 * This is static data that includes every known terminal combination to avoid
 * confusion if a terminal pair temporarily disappears from the API.
 * Generated by: scripts/generate-terminal-connections.ts
 *
 * Data is organized as a Record mapping DepartingTerminalID to an array
 * of all TerminalMate connections from that terminal.
 */

import type { TerminalMate } from "ws-dottie/wsf-schedule";
import { getTerminalLocationById } from "./terminalLocations";

/**
 * Complete list of all known terminal connections, organized by departing terminal ID.
 * This data represents all possible terminal pairs in the WSF system,
 * collected from the next 90 days of schedule data.
 * Key: DepartingTerminalID
 * Value: Array of all TerminalMate connections from that terminal
 */
export const TERMINAL_CONNECTIONS: Record<number, TerminalMate[]> = {
  1: [
    {
      DepartingTerminalID: 1,
      DepartingDescription: "Anacortes",
      ArrivingTerminalID: 10,
      ArrivingDescription: "Friday Harbor",
    },
    {
      DepartingTerminalID: 1,
      DepartingDescription: "Anacortes",
      ArrivingTerminalID: 13,
      ArrivingDescription: "Lopez Island",
    },
    {
      DepartingTerminalID: 1,
      DepartingDescription: "Anacortes",
      ArrivingTerminalID: 15,
      ArrivingDescription: "Orcas Island",
    },
    {
      DepartingTerminalID: 1,
      DepartingDescription: "Anacortes",
      ArrivingTerminalID: 18,
      ArrivingDescription: "Shaw Island",
    },
  ],
  3: [
    {
      DepartingTerminalID: 3,
      DepartingDescription: "Bainbridge Island",
      ArrivingTerminalID: 7,
      ArrivingDescription: "Seattle",
    },
  ],
  4: [
    {
      DepartingTerminalID: 4,
      DepartingDescription: "Bremerton",
      ArrivingTerminalID: 7,
      ArrivingDescription: "Seattle",
    },
  ],
  5: [
    {
      DepartingTerminalID: 5,
      DepartingDescription: "Clinton",
      ArrivingTerminalID: 14,
      ArrivingDescription: "Mukilteo",
    },
  ],
  7: [
    {
      DepartingTerminalID: 7,
      DepartingDescription: "Seattle",
      ArrivingTerminalID: 3,
      ArrivingDescription: "Bainbridge Island",
    },
    {
      DepartingTerminalID: 7,
      DepartingDescription: "Seattle",
      ArrivingTerminalID: 4,
      ArrivingDescription: "Bremerton",
    },
  ],
  8: [
    {
      DepartingTerminalID: 8,
      DepartingDescription: "Edmonds",
      ArrivingTerminalID: 12,
      ArrivingDescription: "Kingston",
    },
  ],
  9: [
    {
      DepartingTerminalID: 9,
      DepartingDescription: "Fauntleroy",
      ArrivingTerminalID: 20,
      ArrivingDescription: "Southworth",
    },
    {
      DepartingTerminalID: 9,
      DepartingDescription: "Fauntleroy",
      ArrivingTerminalID: 22,
      ArrivingDescription: "Vashon Island",
    },
  ],
  10: [
    {
      DepartingTerminalID: 10,
      DepartingDescription: "Friday Harbor",
      ArrivingTerminalID: 1,
      ArrivingDescription: "Anacortes",
    },
    {
      DepartingTerminalID: 10,
      DepartingDescription: "Friday Harbor",
      ArrivingTerminalID: 13,
      ArrivingDescription: "Lopez Island",
    },
    {
      DepartingTerminalID: 10,
      DepartingDescription: "Friday Harbor",
      ArrivingTerminalID: 15,
      ArrivingDescription: "Orcas Island",
    },
    {
      DepartingTerminalID: 10,
      DepartingDescription: "Friday Harbor",
      ArrivingTerminalID: 18,
      ArrivingDescription: "Shaw Island",
    },
  ],
  11: [
    {
      DepartingTerminalID: 11,
      DepartingDescription: "Coupeville ",
      ArrivingTerminalID: 17,
      ArrivingDescription: "Port Townsend",
    },
  ],
  12: [
    {
      DepartingTerminalID: 12,
      DepartingDescription: "Kingston",
      ArrivingTerminalID: 8,
      ArrivingDescription: "Edmonds",
    },
  ],
  13: [
    {
      DepartingTerminalID: 13,
      DepartingDescription: "Lopez Island",
      ArrivingTerminalID: 1,
      ArrivingDescription: "Anacortes",
    },
    {
      DepartingTerminalID: 13,
      DepartingDescription: "Lopez Island",
      ArrivingTerminalID: 10,
      ArrivingDescription: "Friday Harbor",
    },
    {
      DepartingTerminalID: 13,
      DepartingDescription: "Lopez Island",
      ArrivingTerminalID: 15,
      ArrivingDescription: "Orcas Island",
    },
    {
      DepartingTerminalID: 13,
      DepartingDescription: "Lopez Island",
      ArrivingTerminalID: 18,
      ArrivingDescription: "Shaw Island",
    },
  ],
  14: [
    {
      DepartingTerminalID: 14,
      DepartingDescription: "Mukilteo",
      ArrivingTerminalID: 5,
      ArrivingDescription: "Clinton",
    },
  ],
  15: [
    {
      DepartingTerminalID: 15,
      DepartingDescription: "Orcas Island",
      ArrivingTerminalID: 1,
      ArrivingDescription: "Anacortes",
    },
    {
      DepartingTerminalID: 15,
      DepartingDescription: "Orcas Island",
      ArrivingTerminalID: 10,
      ArrivingDescription: "Friday Harbor",
    },
    {
      DepartingTerminalID: 15,
      DepartingDescription: "Orcas Island",
      ArrivingTerminalID: 13,
      ArrivingDescription: "Lopez Island",
    },
    {
      DepartingTerminalID: 15,
      DepartingDescription: "Orcas Island",
      ArrivingTerminalID: 18,
      ArrivingDescription: "Shaw Island",
    },
  ],
  16: [
    {
      DepartingTerminalID: 16,
      DepartingDescription: "Point Defiance",
      ArrivingTerminalID: 21,
      ArrivingDescription: "Tahlequah",
    },
  ],
  17: [
    {
      DepartingTerminalID: 17,
      DepartingDescription: "Port Townsend",
      ArrivingTerminalID: 11,
      ArrivingDescription: "Coupeville ",
    },
  ],
  18: [
    {
      DepartingTerminalID: 18,
      DepartingDescription: "Shaw Island",
      ArrivingTerminalID: 1,
      ArrivingDescription: "Anacortes",
    },
    {
      DepartingTerminalID: 18,
      DepartingDescription: "Shaw Island",
      ArrivingTerminalID: 10,
      ArrivingDescription: "Friday Harbor",
    },
    {
      DepartingTerminalID: 18,
      DepartingDescription: "Shaw Island",
      ArrivingTerminalID: 13,
      ArrivingDescription: "Lopez Island",
    },
    {
      DepartingTerminalID: 18,
      DepartingDescription: "Shaw Island",
      ArrivingTerminalID: 15,
      ArrivingDescription: "Orcas Island",
    },
  ],
  20: [
    {
      DepartingTerminalID: 20,
      DepartingDescription: "Southworth",
      ArrivingTerminalID: 9,
      ArrivingDescription: "Fauntleroy",
    },
    {
      DepartingTerminalID: 20,
      DepartingDescription: "Southworth",
      ArrivingTerminalID: 22,
      ArrivingDescription: "Vashon Island",
    },
  ],
  21: [
    {
      DepartingTerminalID: 21,
      DepartingDescription: "Tahlequah",
      ArrivingTerminalID: 16,
      ArrivingDescription: "Point Defiance",
    },
  ],
  22: [
    {
      DepartingTerminalID: 22,
      DepartingDescription: "Vashon Island",
      ArrivingTerminalID: 9,
      ArrivingDescription: "Fauntleroy",
    },
    {
      DepartingTerminalID: 22,
      DepartingDescription: "Vashon Island",
      ArrivingTerminalID: 20,
      ArrivingDescription: "Southworth",
    },
  ],
};

/**
 * Get all unique departing terminal IDs from connections.
 *
 * @param connections - Record of terminal connections by departing terminal ID
 * @returns Array of unique departing terminal IDs, sorted ascending
 */
export const getUniqueDepartingTerminalIds = (
  connections: Record<number, TerminalMate[]>
): number[] => {
  return Object.keys(connections)
    .map(Number)
    .sort((a, b) => a - b);
};

/**
 * Get reachable destination terminals for a given departing terminal.
 *
 * @param connections - Record of terminal connections by departing terminal ID
 * @param departingTerminalId - ID of the departing terminal
 * @returns Array of arriving terminal IDs that can be reached from the departing terminal
 */
export const getReachableDestinations = (
  connections: Record<number, TerminalMate[]>,
  departingTerminalId: number
): number[] => {
  const terminalConnections = connections[departingTerminalId];
  if (!terminalConnections) {
    return [];
  }
  return terminalConnections.map((c) => c.ArrivingTerminalID);
};

/**
 * Transform terminal connections into a structure suitable for UI display.
 * Maps terminal IDs to abbreviations and full names using terminalLocations data.
 *
 * @param connections - Record of terminal connections by departing terminal ID
 * @returns Array of terminal cards data, each with terminal info and destinations
 */
export type TerminalCardData = {
  terminalId: number;
  terminalName: string;
  terminalSlug: string;
  destinations: Array<{
    terminalId: number;
    terminalName: string;
    terminalSlug: string;
  }>;
};

export const transformConnectionsToTerminalCards = (
  connections: Record<number, TerminalMate[]>
): TerminalCardData[] => {
  const uniqueDepartingIds = getUniqueDepartingTerminalIds(connections);
  const cards: TerminalCardData[] = [];

  for (const departingId of uniqueDepartingIds) {
    const terminalLocation = getTerminalLocationById(departingId);
    if (!terminalLocation) {
      // Skip terminals not found in terminalLocations data
      continue;
    }

    const destinations = getReachableDestinations(connections, departingId);
    const destinationData = destinations
      .map((arrivingId) => {
        const arrivingLocation = getTerminalLocationById(arrivingId);
        if (!arrivingLocation) {
          return null;
        }
        return {
          terminalId: arrivingId,
          terminalName: arrivingLocation.TerminalName,
          terminalSlug: arrivingLocation.TerminalAbbrev.toLowerCase(),
        };
      })
      .filter((d): d is NonNullable<typeof d> => d !== null);

    cards.push({
      terminalId: departingId,
      terminalName: terminalLocation.TerminalName,
      terminalSlug: terminalLocation.TerminalAbbrev.toLowerCase(),
      destinations: destinationData,
    });
  }

  // Sort alphabetically by terminal name
  return cards.sort((a, b) => a.terminalName.localeCompare(b.terminalName));
};

/** Number of terminal cards (computed once at module load). Used for parallax width. */
export const NUM_TERMINAL_CARDS =
  transformConnectionsToTerminalCards(TERMINAL_CONNECTIONS).length;

/** Total carousel items including the blank placeholder at index 0. */
export const TOTAL_CAROUSEL_ITEMS = NUM_TERMINAL_CARDS + 1;
